print("Dame 3 números y te diré cuál es el mayor y el menor.")
num1 = int(input("Cuál sería el primero? -->"))
num2 = int(input("Ahora el segundo -->"))
num3 = int(input("Con este ya tendríamos los 3 :D -->"))
print(f"Tus números son el {num1}, el {num2} y el {num3}")
print('El número más grande es el')
print(max(num1, num2, num3))
print("El número más pequeño es el")
print(min(num1, num2, num3))
print("La suma de los 3 da")
print(num1 + num2 + num3)
print("Y si los restamos dan")
print(num1 - num2 - num3)
